version: '3.7'

services:
  todo-db:
    image: diamol/postgres:11.5
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - type: bind
        source: C:\data\postgres
        target: /var/lib/postgresql/data
    networks:
      - app-net
  
  todo-web:
    image: diamol/ch06-todo-list
    restart: unless-stopped
    ports:
      - "8040:80"
    environment:
      - Database:Provider=Postgres
    depends_on:
      - todo-db
    networks:
      - app-net
    secrets:
      - source: postgres-connection
        target: /app/config/secrets.json

networks:
  app-net:
    external:
      name: nat

secrets:
  postgres-connection:
    file: postgres-connection.json